apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: local-docker-sample-app
  labels:
    app: local-docker-sample-app
    sample: local-docker-images
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: local-docker-sample-app
        sample: local-docker-images
    spec:
      containers:
      - name: local-docker-sample-app
        image: cr.lab304.org/sample-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
