apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  labels:
    app: local-docker-sample-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: local-docker-sample-app
