apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-pv-test
  labels:
    app: nginx-pv-test
    sample: persistent-volumes-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-pv-test
        sample: local-docker-images
    spec:
      containers:
      - name: nginx-pv-test
        image: nginx
        ports:
        - name: "http-server"
          containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mypv
      volumes:
        - name: mypv
          persistentVolumeClaim:
            claimName: pv-claim
        - name: test-volume
          hostPath:
            path: /data/hosted
