apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
      app: nginx-pv-test
      sample: persistent-volumes-example
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0001/
