apiVersion: v1
kind: Service
metadata:
  name: nginx-pv-service
  labels:
      app: nginx-pv-test
      sample: persistent-volumes-example
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: nginx-pv-test
