apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-hosted-volume
  labels:
    app: nginx-hosted-volume
    sample: volumes-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-hosted-volume
        sample: volumes-example
    spec:
      containers:
      - name: nginx-pv-test
        image: nginx
        ports:
        - name: "http-server"
          containerPort: 80
        volumeMounts:
        - name: volume-example
          mountPath: "/usr/share/nginx/html"
      volumes:
        - name: volume-example
          hostPath:
            path: /data/hosted
