apiVersion: v1
kind: Service
metadata:
  name: nginx-hosted-volume
  labels:
      app: nginx-hosted-volume
      sample: volumes-example
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: nginx-hosted-volume
